version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: kishan
      POSTGRES_DB: getsetdsadb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
